import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useAuth, signOut } from "@/hooks/use-auth";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import {
  Download, Trash2, Mail, Search, FileText, LogOut, Loader2,
  User as UserIcon, Calendar, Sparkles, MessageCircle,
} from "lucide-react";
import { listReports, deleteReport, getReportSignedUrl } from "@/lib/reports.functions";
import { emailReportPdf } from "@/lib/email-pdf.functions";
import { openExternal } from "@/lib/external-link";
import { openWhatsApp } from "@/lib/whatsapp";
import { supabase } from "@/integrations/supabase/client";

const WHATSAPP = "918897230858";

export const Route = createFileRoute("/_authenticated/dashboard")({
  head: () => ({ meta: [{ title: "Dashboard · Manoj Wheels" }] }),
  component: Dashboard,
});

type ReportRow = {
  id: string;
  email: string;
  report_type: string;
  title: string | null;
  summary: string | null;
  score: number;
  recommendation: string | null;
  tread: number | null;
  cracks: string | null;
  remaining_km: number | null;
  confidence: number | null;
  notes: string | null;
  pdf_path: string | null;
  created_at: string;
};

const REPORT_LABEL: Record<string, string> = {
  "ai-tyre-check": "AI Tyre Check",
  "tyre-mileage": "Tyre Mileage",
  "tyre-size": "Tyre Size",
  "tyre-pressure": "Tyre Pressure",
  "fuel-savings": "Fuel Savings",
  "service-cost": "Service Cost",
};

function Dashboard() {
  const { user } = useAuth();
  const list = useServerFn(listReports);
  const del = useServerFn(deleteReport);
  const sign = useServerFn(getReportSignedUrl);
  const sendEmail = useServerFn(emailReportPdf);

  const [reports, setReports] = useState<ReportRow[] | null>(null);
  const [search, setSearch] = useState("");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [busyId, setBusyId] = useState<string | null>(null);
  const [emailOpen, setEmailOpen] = useState<string | null>(null);
  const [emailVal, setEmailVal] = useState("");
  const [emailSending, setEmailSending] = useState(false);

  async function refresh() {
    try {
      const rows = await list({ data: {
        search: search || undefined,
        from: fromDate ? new Date(fromDate).toISOString() : undefined,
        to: toDate ? new Date(toDate + "T23:59:59").toISOString() : undefined,
      } });
      setReports(rows as ReportRow[]);
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to load reports");
    }
  }

  useEffect(() => { refresh(); /* eslint-disable-next-line */ }, []);

  const stats = useMemo(() => {
    if (!reports) return { total: 0, avg: 0, replace: 0 };
    const total = reports.length;
    const avg = total ? Math.round(reports.reduce((s, r) => s + (r.score ?? 0), 0) / total) : 0;
    const replace = reports.filter(r => r.recommendation === "Replace Immediately").length;
    return { total, avg, replace };
  }, [reports]);

  async function handleDownload(r: ReportRow) {
    setBusyId(r.id);
    try {
      if (!r.pdf_path) throw new Error("PDF not generated for this report.");
      const { signedUrl } = await sign({ data: { reportId: r.id } });
      window.open(signedUrl, "_blank", "noopener");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Could not get PDF");
    } finally { setBusyId(null); }
  }

  async function handleWhatsApp(r: ReportRow) {
    setBusyId(r.id);
    try {
      let pdfLine = "";
      if (r.pdf_path) {
        const { signedUrl } = await sign({ data: { reportId: r.id } });
        pdfLine = `\nView Report:\n${signedUrl}\n`;
      }
      const date = new Date(r.created_at).toLocaleDateString("en-GB").replaceAll("/", "-");
      const toolLabel = REPORT_LABEL[r.report_type] ?? "Report";
      const text =
        `🚗 *Manoj Wheels — ${r.title ?? toolLabel}*\n\n` +
        (r.summary ? `${r.summary}\n` : `Score: ${r.score}/100\n`) +
        `Date: ${date}\n` +
        (r.recommendation ? `Recommendation: ${r.recommendation}\n` : "") +
        pdfLine +
        `\nGenerated by Manoj Wheels.`;
      openWhatsApp(WHATSAPP, text);
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Could not prepare WhatsApp share");
    } finally { setBusyId(null); }
  }

  async function handleDelete(r: ReportRow) {
    if (!confirm("Delete this report permanently?")) return;
    setBusyId(r.id);
    try {
      await del({ data: { reportId: r.id } });
      setReports(reports?.filter(x => x.id !== r.id) ?? null);
      toast.success("Report deleted");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to delete");
    } finally { setBusyId(null); }
  }

  async function handleSendEmail() {
    if (!emailOpen) return;
    const ok = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emailVal);
    if (!ok) return toast.error("Enter a valid email");
    setEmailSending(true);
    try {
      await sendEmail({ data: { reportId: emailOpen, toEmail: emailVal.trim() } });
      toast.success("✓ Email sent successfully");
      setEmailOpen(null);
      setEmailVal("");
    } catch (e) {
      toast.error(`✗ ${e instanceof Error ? e.message : "Failed to send email"}`);
    } finally { setEmailSending(false); }
  }

  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-10 lg:py-14">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl sm:text-4xl font-extrabold">My Dashboard</h1>
          <p className="text-muted-foreground mt-1 text-sm">{user?.email}</p>
        </div>
        <Button variant="outline" onClick={async () => { await signOut(); window.location.href = "/"; }}>
          <LogOut className="w-4 h-4" /> Sign Out
        </Button>
      </div>

      <div className="mt-6 grid sm:grid-cols-3 gap-4">
        <StatCard label="Total Reports" value={stats.total} icon={<FileText className="w-5 h-5 text-primary" />} />
        <StatCard label="Avg Health Score" value={`${stats.avg}/100`} icon={<Sparkles className="w-5 h-5 text-gold" />} />
        <StatCard label="Replace Recommended" value={stats.replace} icon={<Calendar className="w-5 h-5 text-primary" />} />
      </div>

      <Tabs defaultValue="reports" className="mt-8">
        <TabsList>
          <TabsTrigger value="reports"><FileText className="w-4 h-4 mr-1.5" />Reports</TabsTrigger>
          <TabsTrigger value="profile"><UserIcon className="w-4 h-4 mr-1.5" />Profile</TabsTrigger>
        </TabsList>

        <TabsContent value="reports" className="mt-6 space-y-4">
          <Card className="p-4 bg-card/60">
            <div className="grid sm:grid-cols-4 gap-3">
              <div className="sm:col-span-2 relative">
                <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
                <Input className="pl-9" placeholder="Search reports…" value={search} onChange={(e) => setSearch(e.target.value)} />
              </div>
              <Input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} />
              <Input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} />
            </div>
            <div className="flex gap-2 mt-3">
              <Button variant="hero" size="sm" onClick={refresh}>Apply filters</Button>
              <Button variant="ghost" size="sm" onClick={() => { setSearch(""); setFromDate(""); setToDate(""); setTimeout(refresh, 0); }}>Clear</Button>
            </div>
          </Card>

          {reports === null ? (
            <div className="grid gap-3">
              <Skeleton className="h-24" /><Skeleton className="h-24" /><Skeleton className="h-24" />
            </div>
          ) : reports.length === 0 ? (
            <Card className="p-10 text-center bg-card/60">
              <FileText className="w-10 h-10 text-muted-foreground mx-auto" />
              <h3 className="mt-4 font-bold">No reports yet</h3>
              <p className="text-sm text-muted-foreground mt-1">Run any tool to generate your first report.</p>
              <Button asChild variant="hero" className="mt-4"><Link to="/tools">Open Tools Hub</Link></Button>
            </Card>
          ) : (
            <ul className="grid gap-3">
              {reports.map(r => (
                <li key={r.id}>
                  <Card className="p-4 sm:p-5 bg-card/60">
                    <div className="flex flex-wrap gap-4 items-start">
                      <div className="flex items-center gap-3 min-w-0 flex-1">
                        <div className="w-14 h-14 rounded-xl bg-gradient-primary/15 border border-primary/30 flex items-center justify-center shrink-0">
                          <span className="text-xl font-extrabold text-gradient-primary">{r.score}</span>
                        </div>
                        <div className="min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="font-bold truncate">
                              {r.title ?? REPORT_LABEL[r.report_type] ?? "Report"}
                            </span>
                            <Badge variant="outline" className="text-[10px] uppercase">
                              {REPORT_LABEL[r.report_type] ?? r.report_type}
                            </Badge>
                            {r.report_type === "ai-tyre-check" && <RecommendationBadge value={r.recommendation} />}
                            {!r.pdf_path && <Badge variant="outline" className="text-[10px]">No PDF</Badge>}
                          </div>
                          <p className="text-xs text-muted-foreground mt-0.5">
                            {new Date(r.created_at).toLocaleString()}
                            {r.report_type === "ai-tyre-check"
                              ? ` · Tread ${r.tread ?? 0}% · ${r.cracks ?? "—"}`
                              : r.summary
                              ? ` · ${r.summary}`
                              : ""}
                          </p>
                          {r.notes && <p className="text-sm mt-1 text-muted-foreground line-clamp-2">{r.notes}</p>}
                        </div>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        <Button size="sm" variant="hero" disabled={busyId === r.id || !r.pdf_path} onClick={() => handleDownload(r)}>
                          {busyId === r.id ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />} PDF
                        </Button>
                        <Button size="sm" variant="outline" disabled={busyId === r.id} onClick={() => handleWhatsApp(r)}>
                          <MessageCircle className="w-4 h-4" /> WhatsApp
                        </Button>
                        <Button size="sm" variant="outline" disabled={!r.pdf_path} onClick={() => { setEmailOpen(r.id); setEmailVal(user?.email ?? ""); }}>
                          <Mail className="w-4 h-4" /> Email
                        </Button>
                        <Button size="sm" variant="ghost" disabled={busyId === r.id} onClick={() => handleDelete(r)}>
                          <Trash2 className="w-4 h-4 text-primary" />
                        </Button>
                      </div>
                    </div>

                    {emailOpen === r.id && (
                      <div className="mt-4 rounded-lg border border-border bg-background/40 p-3 flex flex-wrap gap-2 items-end">
                        <div className="flex-1 min-w-[200px]">
                          <Label htmlFor={`em-${r.id}`} className="text-xs">Send PDF to email</Label>
                          <Input id={`em-${r.id}`} type="email" value={emailVal} onChange={(e) => setEmailVal(e.target.value)} placeholder="recipient@example.com" />
                        </div>
                        <Button size="sm" variant="hero" onClick={handleSendEmail} disabled={emailSending}>
                          {emailSending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Mail className="w-4 h-4" />} Send
                        </Button>
                        <Button size="sm" variant="ghost" onClick={() => setEmailOpen(null)}>Cancel</Button>
                      </div>
                    )}
                  </Card>
                </li>
              ))}
            </ul>
          )}
        </TabsContent>

        <TabsContent value="profile" className="mt-6">
          <Card className="p-6 bg-card/60 max-w-lg">
            <ProfileTab />
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}

function StatCard({ label, value, icon }: { label: string; value: number | string; icon: React.ReactNode }) {
  return (
    <Card className="p-5 bg-card/60 flex items-center gap-4">
      <div className="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center">{icon}</div>
      <div>
        <p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p>
        <p className="text-2xl font-extrabold">{value}</p>
      </div>
    </Card>
  );
}

function RecommendationBadge({ value }: { value: string | null }) {
  if (!value) return null;
  const cls =
    value === "Safe to Use" ? "bg-[oklch(0.72_0.18_145/0.15)] text-[oklch(0.85_0.18_145)] border-[oklch(0.72_0.18_145/0.4)]"
    : value === "Monitor Soon" ? "bg-gold/15 text-gold border-gold/40"
    : "bg-primary/15 text-primary border-primary/40";
  return <span className={`text-[10px] uppercase tracking-wider px-2 py-0.5 rounded-full border ${cls}`}>{value}</span>;
}

function ProfileTab() {
  const { user } = useAuth();
  const [name, setName] = useState("");
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!user) return;
    supabase.from("profiles").select("full_name").eq("id", user.id).maybeSingle().then(({ data }) => {
      setName(data?.full_name ?? (user.user_metadata?.full_name as string) ?? "");
      setLoading(false);
    });
  }, [user]);

  async function save() {
    if (!user) return;
    setSaving(true);
    const { error } = await supabase.from("profiles").update({ full_name: name }).eq("id", user.id);
    setSaving(false);
    if (error) toast.error(error.message);
    else toast.success("Profile saved");
  }

  if (loading) return <Skeleton className="h-32" />;

  return (
    <div className="space-y-4">
      <div>
        <Label>Email</Label>
        <Input value={user?.email ?? ""} disabled />
      </div>
      <div>
        <Label htmlFor="fn">Full Name</Label>
        <Input id="fn" value={name} onChange={(e) => setName(e.target.value)} />
      </div>
      <Button onClick={save} variant="hero" disabled={saving}>
        {saving && <Loader2 className="w-4 h-4 animate-spin" />} Save
      </Button>
    </div>
  );
}
