/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TyreLifeRouteImport } from './routes/tyre-life'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiCheckRouteImport } from './routes/ai-check'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsMileageRouteImport } from './routes/tools.mileage'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const TyreLifeRoute = TyreLifeRouteImport.update({
  id: '/tyre-life',
  path: '/tyre-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCheckRoute = AiCheckRouteImport.update({
  id: '/ai-check',
  path: '/ai-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMileageRoute = ToolsMileageRouteImport.update({
  id: '/mileage',
  path: '/mileage',
  getParentRoute: () => ToolsRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-check': typeof AiCheckRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tyre-life': typeof TyreLifeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/mileage': typeof ToolsMileageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-check': typeof AiCheckRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tyre-life': typeof TyreLifeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/mileage': typeof ToolsMileageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-check': typeof AiCheckRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tyre-life': typeof TyreLifeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/mileage': typeof ToolsMileageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-check'
    | '/auth'
    | '/book'
    | '/contact'
    | '/services'
    | '/tools'
    | '/tyre-life'
    | '/dashboard'
    | '/tools/mileage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-check'
    | '/auth'
    | '/book'
    | '/contact'
    | '/services'
    | '/tools'
    | '/tyre-life'
    | '/dashboard'
    | '/tools/mileage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-check'
    | '/auth'
    | '/book'
    | '/contact'
    | '/services'
    | '/tools'
    | '/tyre-life'
    | '/_authenticated/dashboard'
    | '/tools/mileage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiCheckRoute: typeof AiCheckRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  TyreLifeRoute: typeof TyreLifeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tyre-life': {
      id: '/tyre-life'
      path: '/tyre-life'
      fullPath: '/tyre-life'
      preLoaderRoute: typeof TyreLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-check': {
      id: '/ai-check'
      path: '/ai-check'
      fullPath: '/ai-check'
      preLoaderRoute: typeof AiCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/mileage': {
      id: '/tools/mileage'
      path: '/mileage'
      fullPath: '/tools/mileage'
      preLoaderRoute: typeof ToolsMileageRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ToolsRouteChildren {
  ToolsMileageRoute: typeof ToolsMileageRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsMileageRoute: ToolsMileageRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiCheckRoute: AiCheckRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  ToolsRoute: ToolsRouteWithChildren,
  TyreLifeRoute: TyreLifeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
