/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TyreLifeRouteImport } from './routes/tyre-life'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiCheckRouteImport } from './routes/ai-check'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsTyreSizeCalculatorRouteImport } from './routes/tools.tyre-size-calculator'
import { Route as ToolsTyrePressureCalculatorRouteImport } from './routes/tools.tyre-pressure-calculator'
import { Route as ToolsTyreMileageCalculatorRouteImport } from './routes/tools.tyre-mileage-calculator'
import { Route as ToolsFuelSavingsCalculatorRouteImport } from './routes/tools.fuel-savings-calculator'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const TyreLifeRoute = TyreLifeRouteImport.update({
  id: '/tyre-life',
  path: '/tyre-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCheckRoute = AiCheckRouteImport.update({
  id: '/ai-check',
  path: '/ai-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTyreSizeCalculatorRoute = ToolsTyreSizeCalculatorRouteImport.update({
  id: '/tools/tyre-size-calculator',
  path: '/tools/tyre-size-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTyrePressureCalculatorRoute =
  ToolsTyrePressureCalculatorRouteImport.update({
    id: '/tools/tyre-pressure-calculator',
    path: '/tools/tyre-pressure-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsTyreMileageCalculatorRoute =
  ToolsTyreMileageCalculatorRouteImport.update({
    id: '/tools/tyre-mileage-calculator',
    path: '/tools/tyre-mileage-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsFuelSavingsCalculatorRoute =
  ToolsFuelSavingsCalculatorRouteImport.update({
    id: '/tools/fuel-savings-calculator',
    path: '/tools/fuel-savings-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-check': typeof AiCheckRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/tyre-life': typeof TyreLifeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/fuel-savings-calculator': typeof ToolsFuelSavingsCalculatorRoute
  '/tools/tyre-mileage-calculator': typeof ToolsTyreMileageCalculatorRoute
  '/tools/tyre-pressure-calculator': typeof ToolsTyrePressureCalculatorRoute
  '/tools/tyre-size-calculator': typeof ToolsTyreSizeCalculatorRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-check': typeof AiCheckRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/tyre-life': typeof TyreLifeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/fuel-savings-calculator': typeof ToolsFuelSavingsCalculatorRoute
  '/tools/tyre-mileage-calculator': typeof ToolsTyreMileageCalculatorRoute
  '/tools/tyre-pressure-calculator': typeof ToolsTyrePressureCalculatorRoute
  '/tools/tyre-size-calculator': typeof ToolsTyreSizeCalculatorRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-check': typeof AiCheckRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/tyre-life': typeof TyreLifeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/fuel-savings-calculator': typeof ToolsFuelSavingsCalculatorRoute
  '/tools/tyre-mileage-calculator': typeof ToolsTyreMileageCalculatorRoute
  '/tools/tyre-pressure-calculator': typeof ToolsTyrePressureCalculatorRoute
  '/tools/tyre-size-calculator': typeof ToolsTyreSizeCalculatorRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-check'
    | '/auth'
    | '/book'
    | '/contact'
    | '/services'
    | '/tyre-life'
    | '/dashboard'
    | '/tools/fuel-savings-calculator'
    | '/tools/tyre-mileage-calculator'
    | '/tools/tyre-pressure-calculator'
    | '/tools/tyre-size-calculator'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-check'
    | '/auth'
    | '/book'
    | '/contact'
    | '/services'
    | '/tyre-life'
    | '/dashboard'
    | '/tools/fuel-savings-calculator'
    | '/tools/tyre-mileage-calculator'
    | '/tools/tyre-pressure-calculator'
    | '/tools/tyre-size-calculator'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-check'
    | '/auth'
    | '/book'
    | '/contact'
    | '/services'
    | '/tyre-life'
    | '/_authenticated/dashboard'
    | '/tools/fuel-savings-calculator'
    | '/tools/tyre-mileage-calculator'
    | '/tools/tyre-pressure-calculator'
    | '/tools/tyre-size-calculator'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiCheckRoute: typeof AiCheckRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  TyreLifeRoute: typeof TyreLifeRoute
  ToolsFuelSavingsCalculatorRoute: typeof ToolsFuelSavingsCalculatorRoute
  ToolsTyreMileageCalculatorRoute: typeof ToolsTyreMileageCalculatorRoute
  ToolsTyrePressureCalculatorRoute: typeof ToolsTyrePressureCalculatorRoute
  ToolsTyreSizeCalculatorRoute: typeof ToolsTyreSizeCalculatorRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tyre-life': {
      id: '/tyre-life'
      path: '/tyre-life'
      fullPath: '/tyre-life'
      preLoaderRoute: typeof TyreLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-check': {
      id: '/ai-check'
      path: '/ai-check'
      fullPath: '/ai-check'
      preLoaderRoute: typeof AiCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tyre-size-calculator': {
      id: '/tools/tyre-size-calculator'
      path: '/tools/tyre-size-calculator'
      fullPath: '/tools/tyre-size-calculator'
      preLoaderRoute: typeof ToolsTyreSizeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tyre-pressure-calculator': {
      id: '/tools/tyre-pressure-calculator'
      path: '/tools/tyre-pressure-calculator'
      fullPath: '/tools/tyre-pressure-calculator'
      preLoaderRoute: typeof ToolsTyrePressureCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tyre-mileage-calculator': {
      id: '/tools/tyre-mileage-calculator'
      path: '/tools/tyre-mileage-calculator'
      fullPath: '/tools/tyre-mileage-calculator'
      preLoaderRoute: typeof ToolsTyreMileageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/fuel-savings-calculator': {
      id: '/tools/fuel-savings-calculator'
      path: '/tools/fuel-savings-calculator'
      fullPath: '/tools/fuel-savings-calculator'
      preLoaderRoute: typeof ToolsFuelSavingsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiCheckRoute: AiCheckRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  TyreLifeRoute: TyreLifeRoute,
  ToolsFuelSavingsCalculatorRoute: ToolsFuelSavingsCalculatorRoute,
  ToolsTyreMileageCalculatorRoute: ToolsTyreMileageCalculatorRoute,
  ToolsTyrePressureCalculatorRoute: ToolsTyrePressureCalculatorRoute,
  ToolsTyreSizeCalculatorRoute: ToolsTyreSizeCalculatorRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
